version: '3.8'

services:
  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-assistant-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_TYPE=sqlite
      - SQLITE_DATABASE_PATH=/app/data/sql/team_mock.db
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./chroma_db:/app/chroma_db
    networks:
      - llm-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: llm-assistant-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U llm_assistant -d llm_assistant_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - llm-network
    restart: unless-stopped

  # Ollama
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: llm-assistant-ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - llm-network
  #   restart: unless-stopped

  # pgAdmin 
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: llm-assistant-pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - llm-network

networks:
  llm-network:
    driver: bridge

volumes:
  postgres_data:
  chroma_data:
  # ollama_data:  