[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#2c3e50"
font = "sans serif"

[server]
port = 8501
headless = true
runOnSave = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
